version: '3.8'

services:
  # Servidor Java (Spring Boot)
  chat-server:
    build: 
      context: ./part1/server/java
      dockerfile: Dockerfile
    container_name: distributed-chat-server
    ports:
      - "8080:8080"
    volumes:
      - chat-data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/request", "-X", "POST", "-H", "Content-Type: application/json", "-d", "{\"service\":\"users\",\"data\":{\"timestamp\":\"\"}}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Cliente Go
  chat-client-1:
    build:
      context: ./part1/client/go
      dockerfile: Dockerfile
    container_name: distributed-chat-client-1
    depends_on:
      chat-server:
        condition: service_healthy
    environment:
      - SERVER_URL=http://chat-server:8080
    networks:
      - chat-network
    command: ["./main"]
    stdin_open: true
    tty: true
    restart: "no"

  # Cliente Go adicional para teste (opcional)
  chat-client-2:
    build:
      context: ./part1/client/go
      dockerfile: Dockerfile
    container_name: distributed-chat-client-2
    depends_on:
      chat-server:
        condition: service_healthy
    environment:
      - SERVER_URL=http://chat-server:8080
    networks:
      - chat-network
    command: ["./main"]
    stdin_open: true
    tty: true
    restart: "no"
    profiles:
      - multi-client

networks:
  chat-network:
    driver: bridge

volumes:
  chat-data:
    driver: local
